Repository akaihola/graylint, pull requests merged in 2024-07, with the labels that each got.

#40 Pass "graylint" to config dump function to get the correct configuration section name
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
  src/graylint/__main__.py
Labels: bug

#45 Modernize type hints in `linting.py`
  src/graylint/linting.py
Labels: CI

#41 Fix version reporting for argparser
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
  src/graylint/command_line.py
Labels: bug

#44 Fix CI compatibility with Pip >= 24.1
  .github/workflows/pylint.yml
  CHANGES.rst
  constraints-oldest.txt
  setup.cfg
Labels: bug, CI

#46 Release 1.1.2
  CHANGES.rst
  README.rst
  action.yml
  src/graylint/version.py
Labels: release

#47 Refine exit codes
  CHANGES.rst
  constraints-oldest.txt
  pyproject.toml
  setup.cfg
  src/graylint/__main__.py
  src/graylint/tests/test_command_line.py
  src/graylint/tests/test_main.py
Labels: enhancement

#48 Release 2.0.0
  CHANGES.rst
  README.rst
  action.yml
  src/graylint/version.py
Labels: release
